# Generated by Django 5.2.8 on 2026-02-24 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True, null=True, unique=True)),
                ('is_top_4000', models.BooleanField(default=False, verbose_name='Top 4000 Common Word')),
            ],
            options={
                'verbose_name': 'English Word',
                'verbose_name_plural': 'English Words',
                'db_table': 'english_words',
            },
        ),
        migrations.CreateModel(
            name='PolishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lexentry', models.TextField(blank=True, null=True, unique=True)),
                ('word', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Polish Word',
                'verbose_name_plural': 'Polish Words',
                'db_table': 'polish_words',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=20, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('correct_count', models.IntegerField(default=0)),
                ('total_time_spent_seconds', models.IntegerField(default=0)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('user_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.quiz')),
                ('word', models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, to='core.englishword')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'db_table': 'quiz_questions',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'search_history',
            },
        ),
        migrations.CreateModel(
            name='WordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(blank=True, null=True)),
                ('part_of_speech', models.TextField(blank=True, null=True)),
                ('min_sense_num', models.IntegerField(blank=True, null=True)),
                ('importance', models.FloatField(blank=True, null=True)),
                ('translation_score', models.FloatField(blank=True, null=True)),
                ('english_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.englishword')),
                ('polish_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.polishword')),
            ],
            options={
                'verbose_name': 'Word Definition',
                'verbose_name_plural': 'Word Definitions',
                'db_table': 'word_definitions',
            },
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Word List',
                'verbose_name_plural': 'Word Lists',
                'db_table': 'word_lists',
            },
        ),
        migrations.CreateModel(
            name='WordListMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, to='core.englishword')),
                ('word_list', models.ForeignKey(db_column='list_id', on_delete=django.db.models.deletion.CASCADE, to='core.wordlist')),
            ],
            options={
                'db_table': 'word_lists_membership',
                'unique_together': {('word', 'word_list')},
            },
        ),
        migrations.AddField(
            model_name='wordlist',
            name='words',
            field=models.ManyToManyField(related_name='contained_in_lists', through='core.WordListMembership', to='core.englishword'),
        ),
        migrations.CreateModel(
            name='UserEnglishVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_status', models.CharField(default='new', max_length=20)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.englishword')),
            ],
            options={
                'verbose_name': 'User English Vocabulary',
                'verbose_name_plural': 'User English Vocabularies',
                'db_table': 'user_english_vocabulary',
                'unique_together': {('user', 'word')},
            },
        ),
    ]
